name: Deploy Python FastAPI to EC2

on:
  push:
    branches: [ "master" ]
    paths:
      - "python/**"

jobs:
  deploy-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Python source to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "python/*"
          target: "/home/ubuntu/apps/python/"

      - name: Install Dependencies & Restart Python Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/apps/python
            if [ ! -d .venv ]; then python3 -m venv .venv; fi
            . .venv/bin/activate
            pip install -U pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            sudo systemctl restart python.service
