name: Python CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload Python source to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "python/*"
          target: "/home/ubuntu/apps/python/"

      - name: Restart Python
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/apps/python
            if [ ! -d .venv ]; then python3 -m venv .venv; fi
            . .venv/bin/activate
            pip install -U pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pkill -f 'uvicorn' || true
            nohup .venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 > python.log 2>&1 &
