name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches: [ master ]
    paths:
      - "backEnd/**"
      - ".github/workflows/deploy-backEnd.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build with Gradle
        working-directory: backEnd/alcohol-recommendation
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test
        shell: bash

      - name: Resolve artifact path
        id: artifact
        working-directory: backEnd/alcohol-recommendation
        run: |
          JAR_FILE=$(ls -1t build/libs/*.jar | head -n1)
          echo "jar_path=${JAR_FILE}" >> $GITHUB_OUTPUT
          echo "Resolved: ${JAR_FILE}"

      - name: Prepare remote directory
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/apps/myproject-backend
            sudo chown -R $USER:$USER /home/ubuntu/apps/myproject-backend

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "${{ steps.artifact.outputs.jar_path }}"
          target: "/home/ubuntu/apps/myproject-backend/"

      - name: Restart backend service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/apps/myproject-backend
            LATEST=$(ls -1t *.jar | head -n1)
            cp -f "$LATEST" app.jar
            sudo systemctl restart myproject-backend
            sudo systemctl --no-pager status myproject-backend
