name: Deploy Backend to EC2

on:
    push:
        branches: [ master ]
        paths:
            - 'backEnd/**'
            - '.github/workflows/deploy-backEnd.yml'

concurrency:
    group: deploy-backend
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: 'gradle'

            - name: Setup Gradle (no wrapper)
              uses: gradle/actions/setup-gradle@v3
              with:
                  gradle-version: 8.7

            - name: Build bootJar
              working-directory: backEnd/alcohol-recommendation
              run: |
                  set -e
                  gradle --version
                  gradle clean bootJar -x test
                  echo "== built JARs =="
                  ls -l build/libs
                  # 가장 최신 JAR 경로를 환경변수에 기록
                  LAST_JAR=$(ls -t build/libs/*.jar | head -n1)
                  echo "JAR_PATH=$LAST_JAR" >> $GITHUB_ENV

            - name: Upload JAR to EC2
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  source: "${{ env.JAR_PATH }}"
                  target: "/home/ubuntu/apps/backend/"
                  overwrite: true

            - name: Activate & Restart backend.service
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      set -e
                      mkdir -p /home/ubuntu/apps/backend
                      LATEST_JAR=$(ls -t /home/ubuntu/apps/backend/*.jar | head -n1)
                      echo "LATEST_JAR=$LATEST_JAR"
                      mv "$LATEST_JAR" /home/ubuntu/apps/backend/app.jar
                      chmod 644 /home/ubuntu/apps/backend/app.jar
                      sudo systemctl daemon-reload || true
                      sudo systemctl restart backend
                      sleep 2
                      sudo systemctl status backend --no-pager || true
                      ss -ltnp | grep -E ':8080\b' || (echo 'backend not listening on 8080' && exit 1)
