name: Deploy Python to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Python Source to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "python/*"
          target: "/home/ubuntu/apps/python/"

      - name: Install Dependencies & Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/apps/python
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
            deactivate
            sudo systemctl restart python.service
