name: Deploy Python FastAPI to EC2

on:
  push:
    branches: [ master ] # 브랜치 맞게 수정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare server directory
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/ubuntu/apps/myproject-python

      - name: Upload Python source code
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: python/*
          target: /home/ubuntu/apps/myproject-python

      - name: Restart Python service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl daemon-reload || true
            sudo systemctl restart myproject-python
            sudo systemctl --no-pager status myproject-python
