name: Backend CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Backend
        working-directory: backEnd/alcohol-recommendation
        run: ./gradlew clean build -x test

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backEnd/alcohol-recommendation/build/libs/alcohol-recommendation-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/apps/backend/"

      - name: Restart Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/apps/backend
            pkill -f 'java -jar' || true
            nohup java -jar alcohol-recommendation-0.0.1-SNAPSHOT.jar > backend.log 2>&1 &
