name: CI/CD Python

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-python:
    runs-on: ubuntu-latest
    concurrency:
      group: python-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure deploy dirs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p /opt/apps/python
            sudo chown -R ubuntu:ubuntu /opt/apps

      - name: Copy python sources to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "python/**"
          target: "/opt/apps/python/"
          overwrite: true
          strip_components: 1

      - name: Install deps & restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /opt/apps/python
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            ./venv/bin/pip install --upgrade pip
            if [ -f "requirements.txt" ]; then
              ./venv/bin/pip install -r requirements.txt
            fi
            if pm2 describe fastapi-app >/dev/null 2>&1; then
              pm2 restart fastapi-app
            else
              pm2 start ecosystem.config.js
            fi
            pm2 save
            pm2 status
