name: Deploy Frontend to EC2

on:
    push:
        branches: [ master ]

concurrency:
    group: deploy-frontend
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js 22.16.0
              uses: actions/setup-node@v4
              with:
                  node-version: 22.16.0
                  cache: 'npm'
                  cache-dependency-path: frontEnd/package-lock.json

            - name: Install dependencies
              working-directory: frontEnd
              run: npm ci

            - name: Build
              working-directory: frontEnd
              run: npm run build

            - name: Cleanup target dir on EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      set -e
                      mkdir -p /home/ubuntu/apps/frontend
                      rm -rf /home/ubuntu/apps/frontend/*

            - name: Upload build artifacts to EC2 (strip frontEnd/build/)
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  source: "frontEnd/build/**"
                  target: "/home/ubuntu/apps/frontend/"
                  strip_components: 2
                  overwrite: true

            - name: Nginx sanity check & reload
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      set -e
                      # 업로드 후 실제 배치 상태 확인 (디버깅에 도움)
                      ls -l /home/ubuntu/apps/frontend | sed -n '1,200p'
                      test -f /home/ubuntu/apps/frontend/index.html || (echo "index.html missing" && exit 1)
                      sudo nginx -t
                      sudo systemctl reload nginx || true
