name: Deploy Spring Boot to EC2

on:
  push:
    branches: [ master ]   # main이면 main으로

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      # 백엔드 서브프로젝트만 빌드
      - name: Grant execute permission for Gradlew
        working-directory: backEnd/alcohol-recommendation
        run: chmod +x ./gradlew

      - name: Build backend (Gradle)
        working-directory: backEnd/alcohol-recommendation
        run: ./gradlew clean build -x test

      - name: Find built JAR
        id: jar
        run: |
          FILE=$(ls -1 backEnd/alcohol-recommendation/build/libs/*.jar | head -n1)
          echo "jar=$FILE" >> $GITHUB_OUTPUT
          echo "Found: $FILE"

      - name: Prepare server directory (create if not exists)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/ubuntu/apps/myproject-backend

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ${{ steps.jar.outputs.jar }}
          target: /home/ubuntu/apps/myproject-backend/app.jar
          strip_components: 0

      - name: Restart backend service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl daemon-reload || true
            sudo systemctl restart myproject-backend
            sudo systemctl --no-pager status myproject-backend
