name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./backEnd/alcohol-recommendation/gradlew

      - name: Build with Gradle
        working-directory: ./backEnd/alcohol-recommendation
        run: ./gradlew clean build

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./backEnd/alcohol-recommendation/build/libs/alcohol-recommendation-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/"

      - name: Execute SSH Commands on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Killing existing Spring Boot process if running..."
            screen -S spring-server -X quit || true

            echo "Starting Spring Boot in new screen session..."
            screen -dmS spring-server java -jar /home/ubuntu/alcohol-recommendation-0.0.1-SNAPSHOT.jar